config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  # get '/users' => 'users#index'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show', as: 'user'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy'
  post '/sessions' => 'sessions#create', as: 'sessions'
  get '/libraries' => 'libraries#index'
  get '/libraries/new' => 'libraries#new', as: 'new_library'
  post '/libraries' => 'libraries#create'
  get '/libraries/:id' => 'libraries#show'
  get '/users/:user_id/libraries' => 'library_users#index', as: 'user_libraries'
  post '/libraries/:library_id/users', => 'library_users#create', as: 'library_users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def require_login
      if !current_user
        redirect_to login_path
      end
    end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to libraries_path
  end

  def show
    @library = Library.find(params[:id])
  end

  private

  def library_params
    params.require(:library).permit(:name, :floor_count, :floor_area)
  end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)

    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in."
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login(@user)
      redirect_to @user
    else
      flash[:error] = "Unable to add new user try again"
      redirect_to login_path
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondLibApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Login", login_path %></li>
        <% end %>
    </ul>

    <% flash.each do |name, msg| %>
      <p>
        <small> <%= name.capitalize %>: <%= msg %> </small>
      </p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/libraries/index.html.erb
<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>
  </div>
  <br>
<% end %>

app/views/libraries/new.html.erb
<div class="form-group">
  <%= form_for @library do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "name" %>
  </div>
  <div class="form-group">
    <%= f.number_field :floor_count, placeholder: "floor_count" %>
  </div>
  <div class="form-group">
    <%= f.number_field :floor_area, placeholder: "floor_area" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
    <% end %>
  </div>

</div>

app/views/libraries/show.html.erb
<h1><%= @library.name %></h1>
<p>Floor Count:<%= @library.floor_count %></p>
<p>Floor Area:<%= @library.floor_area %></p>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Welcome to Users Index.</h1>

<div>
There are currently <%= @users.length %> user(s) signed up!
</div>

app/views/users/new.html.erb
<div class="form-group">
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.text_field :first_name, placeholder: "first_name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :last_name, placeholder: "last_name" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, placeholder: "email" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, placeholder: "password" %>
  </div>
  <div class="form-group">
    <%= f.submit "Sign Up" %>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.first_name %> !</h1>
 